on: workflow_dispatch

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

name: SERP results
jobs:
  serp-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master # check out the repo this action is in

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install packages
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/vpn/Windscribe-Stockholm-Ikea.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
      # The openvpn process is automatically terminated in post-action phase

      - name: Run
        run: node scripts/google_search.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ./*.png # or path/to/artifact
