on: workflow_dispatch

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

name: SERP results
jobs:
  serp-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master # check out the repo this action is in

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install packages
        run: npm ci

      - name: Run
        run: node scripts/google_search.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ./*.png # or path/to/artifact
